---
- hosts: localhost
  connection: local
  remote_user: devops
  gather_facts: no
  vars_files:
  - awscreds.yml
  - info.yml
  tasks:
  - name: Basic provisioning of EC2 instance
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: "{{ sipxcom_ami }}"
      instance_type: "{{ large_instance }}"
      key_name: "{{ ssh_keyname }}"
      count: 1
      state: present
      group_id: "{{ secgroup_id }}"
      wait: yes
      vpc_subnet_id: subnet-29a32841
      assign_public_ip: yes
      instance_tags:
        Name: uc1.mihai.test
    register: ec2info
  - name: Print the results
    debug: var=ec2info

  - name: Add all instance public IPs to host group
    add_host: hostname={{ ec2info.instances[0].public_ip  }}
              groups=ec2hosts
              ansible_ssh_private_key_file=~/.ssh/devops-key.pem

  - name: Wait for SSH to come up
    remote_user: root
    wait_for: host={{ ec2info.instances[0].public_ip  }} port=22 delay=10 timeout=320 state=started
